connext/chaindata

- deploy.js
* Fixes https://github.com/connext/chaindata/issues/1 due to `privateKey` type
* Adds `verify()` call to `setup()`
* Add newline to end of file
> Change privateKey to string; Add verify() in setup

- chains.json
Adding info for Portion (PRT) to chains.json
> add PRT eth -> bsc bridge info

- chains.json
deployed v4 to bsc `0x73F059dB0182dc2Ed716D028E1b13033cfcbf63B`
@rhlsthrm  could you please review this PR at your convenience? Thanks
> add mm to bsc

- crossChain.json
Needed for https://github.com/connext/nxtp/pull/201
> Update crossChain.json to hold recommended confirmations count

- crossChain.json
TODO: add more gas stations for each chain we are supporting
> add gas stations param

- crossChain.json
- Update mainnet assets with decimal places
> Add mainnet decimals

- crossChain.json
Fix for https://github.com/connext/monorepo/issues/3893
> Fix #3893: Update crosschain domain ids

- crossChain.json
Add WorkshopToken to Ethereum and Optimism Göerli with address 0x02E82fB078893EC64BC57e55Fe34f6669D8104BC
> Add WorkshopToken

- crossChain.json
> Update crossChain for gastly

- crossChain.json
- Added `Grumpy Cat` chain data mapping
> feat: added grumpyCat token

- crossChain.json
Add Space token xERC20 to ChainData mappings.
> Adding Space Token

- crossChain.json
> fix: add avax domain id

- crossChain.json
Add max fee in eth, derived from [these](https://docs.google.com/spreadsheets/d/134q1uGjL0y5ltthPMfHWX81N9U8SaGXBKFHj-x8cDPg/edit#gid=2068806592) values
> Max fee in eth

- everclear.testnet.staging.json
- Adds asset for everclear testnet staging
> fix: add test asset prices

- everclear.testnet.staging.json
Redeployed staging contracts and subgraphs.
Corresponding deploy PR: https://github.com/defi-wonderland/chimera-monorepo/pull/217
> everclear - redeploy staging 4.1

- everclear.testnet.staging.json
Updates deployment addresses to latest
> fix: testnet staging v4.1 address updates

- everclear.testnet.staging.json
update subgraph urls to latest deployments
> feat: use updated subgraphs

- everclear.testnet.staging.json
fix: update staging deployment
> fix: update staging deployment

- everclear.testnet.staging.json
update subgraphs for audit version
> fix: update subgraphs for audit version

- everclear.testnet.staging.json
Update to latest testnet staging subgraphs and URLs
> feat: update deployments

- everclear.testnet.json
> feat: add prod testnet config

- crossChain.json
Add xPufETH for mapping in Mainnet and BSC network
> feat: add xPufETH in mapping config

- everclear.testnet.json
do not merge until changes from [this pr](https://github.com/defi-wonderland/chimera-monorepo/pull/554) are on testnet prod
> feat: redeploy testnet prod

- everclear.testnet.staging.json
> feat: redeploy staging with everclear as hub

- everclear.json
add studio links for mainnet spokes
> fix: add studio links for mainnet spokes

- everclear.json
> feat: update subgraph urls

- everclear.testnet.json
> chore: update tesntet prod subgraphs

- everclear.testnet.json
add testnet tokenomics hub contracts
> feat: add testnet tokenomics hub contracts

- everclear.json
update mainnet tokenomics addr
> fix: update mainnet tokenomics addr

- everclear.json
- everclear.testnet.json
add tokenomics gateway contracts
> fix: add tokenomics gateway contracts

- everclear.json
> revert: "fix: zircuit latest slug"

- everclear.json
add config for avalance polygon and linea mainnets
> feat: add config for avalance polygon and linea mainnets

- everclear.json
Add WETH, USDC, and USDT to zircuit configuration
> feat: Add WETH, USDC, and USDT to zircuit configuration

- everclear.json
Add Mode and Unichain network configurations
> feat: Add Mode and Unichain network configurations

- everclear.json
network still requires arb update, sync pending
> fix: update arb, hub subgraph urls

- everclear.json
DNM until all subgraphs synced
updates all subgraphs to:
- use latest gold sky URLs
- remove studio URLs (latest version not yet published)
> [DNM] fix: update all subgraphs

- everclear.json
Updates subgraph url to support fee adapter. DNM, not all synced
> chore: update subgraph urls

- everclear.json
> feat: add new chains

- everclear.json
chore: update subgraph URL to version 0.0.3 in everclear.json
> chore: update subgraph URL to version 0.0.3 in everclear.json

- everclear.json
- everclear.mainnet.staging.json
> feat: add safe tx service urls

- everclear.json
Updating gas configs to be zeroed on Polymer supporter chains.
> fix: polymer gas limit config on supported chains
